# Generated by Django 4.0.6 on 2023-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
